export interface Profile {
   id :number ,
   matricule :string
   cnss: string,
   nom :string,
  prenoms :string ,
  nom_conjoint :string,
  sexe :string,
  date_nat :Date,
  tranche_age: number,
  lieux_naissance: string,
  situat_matri :string,
  date_mariage :Date,
  nbr_enfants :number,
  statut :string,
  corps: string,
  categorie_rat: string,
  branche_personnel: string,
  fonction :string,
  ref_nomination :string,
  Date_prise_fonctions: Date,
  responsabilite_particuliere :string,
  grade_paye: string,
  indice_paye :number,
  date_premier_prise_service: Date,
  date_depart_retraite: Date,
  date_prise_service_departement :Date,
  reference_acte_Date_prise_service_poste_actuel :string,
  poste_actuel_service: string,
  type_structure: string,
  commune :string,
  arrondissement :string,
  zone_sanitaire: string,
  poste_specifique :string,
  etat_depart: string,
  poste_anterieurs :string,
  autres_diplome: string,
  rib :string,
  mtn :string,
  celtics :string,
  libercom :string,
  email: string,
  observation_particuliere :string,
  distinction :string,
  reference_distinction :string,
  detail_distinction :string,
  situation_sante :string,
  sanction_punitive :string,
  nature_sanction :string
};

